/* wyrm opcode mnemonics, maintained by hand alongside opcode.h.
 *
 * Indexed by the raw opcode byte (WYRM_OP(code)); a byte no opcode
 * uses is NULL (static storage zero-initializes the rest of the
 * array). */
#ifndef WYRM_OPCODE_NAMES_H
#define WYRM_OPCODE_NAMES_H

static const char* const wy_opcode_names[256] = {
    [0x00] = "noop",
    [0x01] = "trap",
    [0x02] = "return",
    [0x03] = "lnil",
    [0x04] = "lbool",
    [0x05] = "lunset",
    [0x40] = "i8",
    [0x41] = "move",
    [0x42] = "gget",
    [0x43] = "gset",
    [0x45] = "lsym",
    [0x46] = "lconst",
    [0x47] = "import",
    [0x48] = "neg",
    [0x49] = "inv",
    [0x4A] = "not",
    [0x4B] = "jf",
    [0x4C] = "jt",
    [0x4D] = "jerr",
    [0x4E] = "jnerr",
    [0x4F] = "jmp",
    [0x80] = "f32",
    [0x81] = "tuple",
    [0x82] = "list",
    [0x83] = "dict",
    [0x84] = "plist",
    [0x85] = "add",
    [0x86] = "sub",
    [0x87] = "mul",
    [0x88] = "div",
    [0x89] = "mod",
    [0x8A] = "pow",
    [0x8B] = "band",
    [0x8C] = "bor",
    [0x8D] = "shl",
    [0x8E] = "shr",
    [0x8F] = "eq",
    [0x90] = "ne",
    [0x91] = "lt",
    [0x92] = "le",
    [0x93] = "gt",
    [0x94] = "ge",
    [0x95] = "bxor",
    [0x96] = "in",
    [0x97] = "is",
    [0x98] = "getidx",
    [0x99] = "setidx",
    [0x9A] = "getattr",
    [0x9B] = "setattr",
    [0x9C] = "getslot",
    [0x9D] = "setslot",
    [0xA0] = "call",
    [0xA1] = "call_va",
    [0xA2] = "msg",
    [0xA3] = "msg_va",
    [0xA4] = "getmsg",
    [0xA5] = "super",
    [0xA6] = "return_cps",
    [0xA7] = "yield",
    [0xA8] = "closure",
    [0xA9] = "class",
    [0xAA] = "new_instance",
    [0xAB] = "new_primitive",
    [0xAC] = "reg_msg",
    [0xAD] = "defer_reg",
    [0xAE] = "iter",
    [0xAF] = "itnext",
    [0xB0] = "yield_from",
    [0xB1] = "unpack",
    [0xB2] = "cmp3",
    [0xB3] = "getscope",
    [0xB4] = "setscope",
    [0xB5] = "import_star",
    [0xC0] = "i32",
    [0xC1] = "move",
    [0xC2] = "gget",
    [0xC3] = "gset",
    [0xC5] = "lsym",
    [0xC6] = "lconst",
    [0xC7] = "import",
    [0xC8] = "neg",
    [0xC9] = "inv",
    [0xCA] = "not",
    [0xCB] = "jf",
    [0xCC] = "jt",
    [0xCD] = "jerr",
    [0xCE] = "jnerr",
    [0xCF] = "jmp",
};

#endif /* WYRM_OPCODE_NAMES_H */
