#ifndef WYRM_EMBEDDED_BUILTINS_H_
#define WYRM_EMBEDDED_BUILTINS_H_

#include <wyrm/platform/hosted/import_fs.h>

/* Epic 11 M1: the builtin module table - the ported compiler plus the
 * library modules it needs, as checked-in static wy_module_image C sources.
 * Generated by wy/wyrm/tools/embed_build.wy via scripts/regen_builtins.py;
 * the .c files (including the two generated ones listed in the meson
 * sources) are checked in, so neither the build nor meson test produces
 * them. A meson-visible staleness check runs at the end of
 * scripts/run_selfcompile.py.
 *
 * Resolution order: -I roots first (a disk module shadows a builtin), then
 * this table - the expansion VM inherits it through the parent's
 * import_hook/import_ud, which is how std::expand's child finds
 * wyrm::compiler::expand with no file on disk. std::io and std::expand are
 * host modules (src/wyrm/main.c) and deliberately absent from the table. */

extern const wy_import_fs_builtin wyrm_builtin_modules[];
extern const wy_uword wyrm_builtin_module_count;

#endif
