/* Generated by wy/wyrm/tools/embed_build.wy (scripts/regen_builtins.py) - do not edit. */

#include <wyrm/platform/hosted/import_fs.h>

/* Image symbols, defined in embedded_images.c's translation units: */

extern const wy_module_image ctype_image;
extern const wy_module_image pairs_image;
extern const wy_module_image _dsl_image;
extern const wy_module_image ast_image;
extern const wy_module_image bjson_image;
extern const wy_module_image decode_image;
extern const wy_module_image image_image;
extern const wy_module_image opcodes_image;
extern const wy_module_image parser_image;
extern const wy_module_image tokenizer_image;
extern const wy_module_image analysis_image;
extern const wy_module_image classes_image;
extern const wy_module_image context_image;
extern const wy_module_image expand_image;
extern const wy_module_image expansion_image;
extern const wy_module_image expressions_image;
extern const wy_module_image functions_image;
extern const wy_module_image handlers_image;
extern const wy_module_image module_image;
extern const wy_module_image predefined_image;
extern const wy_module_image statements_image;
extern const wy_module_image verify_image;
extern const wy_module_image compiler_image;
extern const wy_module_image compile_source_image;
extern const wy_module_image compiler_main_image;
extern const wy_module_image __init___image;

const wy_import_fs_builtin wyrm_builtin_modules[] = {
    { "std::ctype", &ctype_image },
    { "std::pairs", &pairs_image },
    { "wyrm::_dsl", &_dsl_image },
    { "wyrm::ast", &ast_image },
    { "wyrm::bjson", &bjson_image },
    { "wyrm::decode", &decode_image },
    { "wyrm::image", &image_image },
    { "wyrm::opcodes", &opcodes_image },
    { "wyrm::parser", &parser_image },
    { "wyrm::tokenizer", &tokenizer_image },
    { "wyrm::compiler::analysis", &analysis_image },
    { "wyrm::compiler::classes", &classes_image },
    { "wyrm::compiler::context", &context_image },
    { "wyrm::compiler::expand", &expand_image },
    { "wyrm::compiler::expansion", &expansion_image },
    { "wyrm::compiler::expressions", &expressions_image },
    { "wyrm::compiler::functions", &functions_image },
    { "wyrm::compiler::handlers", &handlers_image },
    { "wyrm::compiler::module", &module_image },
    { "wyrm::compiler::predefined", &predefined_image },
    { "wyrm::compiler::statements", &statements_image },
    { "wyrm::compiler::verify", &verify_image },
    { "wyrm::compiler", &compiler_image },
    { "wyrm::tools::compile_source", &compile_source_image },
    { "wyrm::tools::compiler_main", &compiler_main_image },
    { "wyrm", &__init___image },
    { "bjson", &bjson_image },
    { "opcodes", &opcodes_image },
};

const wy_uword wyrm_builtin_module_count = 28;
