
platform_hosted = {
    'sources'      : files('allocator_cmem.c', 'cmachine.c'),
    'inc'          : [],
    'deps'         : [dependency('threads')],
    'public_inc'   : [],
    'test_sources' : files(
        'test/test_allocator_cmem.cpp'
    ),
    'test_inc'     : [],
    'test_deps'    : [],
}
